#!/bin/bash

flag=0
files=(tests/file_{0..20})
for i in {1..100}
do
    python3 generate.py $1 > res_p
    ./a.out "${files[@]}" > res
    cat res
    cat res_p
    diff res_p res
    if [ $? -ne 0 ]; then
        echo "Test Faild"
        break
        $flag=1
    fi
done

if [ $flag -ne 1 ]; then
    echo "Test Passed"
fi
