#!/bin/bash


flag=0
file="random_sequence.txt"
for i in {1..20}
do
    output=$(python3 generate.py)

    number=$(echo "$output" | cut -d',' -f1)
    message=$(echo "$output" | cut -d',' -f2-)

    echo $message > res
    for p in {1..10}
    do
        ./a.out $p $number $file > my_res
        echo "./a.out" $p $number $file
        cat res
        cat my_res
        diff -w my_res res
        if [ $? -ne 0 ]; then
            echo "Test Faild on sequence"
            flag=1
            cat random_sequence.txt
            break
        fi
    done
    if [ $flag -ne 0 ]; then
        break;
    fi
done

if [ $flag -ne 1 ]; then
    echo "Test Passed"
fi
